let workspaceData =
[
    {
        "menuName" : "Tasks & Messages",
        "hierarchy" : 1,
        "subMenu" :
        [
            {
                "submenuName" : "Task 1",
                "info" : "<b>Task 1</b><br><br><h3>Web Application Development</h3><p>At Equator Technologies, we develop Web Applications which meet the expectations of modern day enterprises. Our web developers deliver exceptional user experience with extreme reliability & high scalability.</p>Technology can make or break companies. Efficient, User-friendly online apps directly impact your revenue. At Equator Technologies, we are aware of this phenomenon and can provide a complete range of solutions for your e-commerce business needs. From web applications to mobile apps to software testing, we provide an array of software development and maintenance services.</p><p>Our technical prowess and extensive experience gives us an edge over our competitors. And that’s not all. We are committed to consistently offering the best IT solutions and enterprise mobility solutions. We understand your company’s budget limitations. That’s why our experts design customized plans to suit your goals, interests and financial needs. We are a rapidly expanding and credible enterprise solution provider. Our top-notch services will not just streamline your workflow, but boost your online presence as well. After all, our goal is to provide swift solutions that are free from hassle! Browse through our services and choose the one that meets your business goals.</p>"
            },
            {
                "submenuName" : "Message 1",
                "info" : "<b>Task 2</b><br><br><h3>Mobile Application Development</h3><p>We specialize in creating Native applications for iOS & Android. We also develop hybrid mobile applications which could be deployed across almost all mobile platforms. We have proven Mobile Application Development expertise.</p><p>Technology can make or break companies. Efficient, User-friendly online apps directly impact your revenue. At Equator Technologies, we are aware of this phenomenon and can provide a complete range of solutions for your e-commerce business needs. From web applications to mobile apps to software testing, we provide an array of software development and maintenance services.</p><p>Our technical prowess and extensive experience gives us an edge over our competitors. And that’s not all. We are committed to consistently offering the best IT solutions and enterprise mobility solutions. We understand your company’s budget limitations. That’s why our experts design customized plans to suit your goals, interests and financial needs. We are a rapidly expanding and credible enterprise solution provider. Our top-notch services will not just streamline your workflow, but boost your online presence as well. After all, our goal is to provide swift solutions that are free from hassle! Browse through our services and choose the one that meets your business goals.</p>"
            },
            {
                "submenuName" : "Task 2",
                "info" : "<b>Task 3</b><br><br><h3>E-commerce Solution</h3><p>Our software developers are highly skilled in developing the most innovative & modern E-commerce apps. Our software developers also come up with powerful strategies to expand our client’s customer base. </p><p>Technology can make or break companies. Efficient, User-friendly online apps directly impact your revenue. At Equator Technologies, we are aware of this phenomenon and can provide a complete range of solutions for your e-commerce business needs. From web applications to mobile apps to software testing, we provide an array of software development and maintenance services.</p><p>Our technical prowess and extensive experience gives us an edge over our competitors. And that’s not all. We are committed to consistently offering the best IT solutions and enterprise mobility solutions. We understand your company’s budget limitations. That’s why our experts design customized plans to suit your goals, interests and financial needs. We are a rapidly expanding and credible enterprise solution provider. Our top-notch services will not just streamline your workflow, but boost your online presence as well. After all, our goal is to provide swift solutions that are free from hassle! Browse through our services and choose the one that meets your business goals.</p>"
            }            
        ]
    },
    {
        "menuName" : "Folders",
        "hierarchy" : 2,
        "subMenu" :
        [
            {
                "submenuName" : "Folder 1",
                "info" : "<b>Folder 1</b><br><br><h3>Web Application Development</h3><p>At Equator Technologies, we develop Web Applications which meet the expectations of modern day enterprises. Our web developers deliver exceptional user experience with extreme reliability & high scalability.</p>Technology can make or break companies. Efficient, User-friendly online apps directly impact your revenue. At Equator Technologies, we are aware of this phenomenon and can provide a complete range of solutions for your e-commerce business needs. From web applications to mobile apps to software testing, we provide an array of software development and maintenance services.</p><p>Our technical prowess and extensive experience gives us an edge over our competitors. And that’s not all. We are committed to consistently offering the best IT solutions and enterprise mobility solutions. We understand your company’s budget limitations. That’s why our experts design customized plans to suit your goals, interests and financial needs. We are a rapidly expanding and credible enterprise solution provider. Our top-notch services will not just streamline your workflow, but boost your online presence as well. After all, our goal is to provide swift solutions that are free from hassle! Browse through our services and choose the one that meets your business goals.</p>"
            },
            {
                "submenuName" : "Folder 2",
                "info" : "<b>Folder 2</b><br><br><h3>Mobile Application Development</h3><p>We specialize in creating Native applications for iOS & Android. We also develop hybrid mobile applications which could be deployed across almost all mobile platforms. We have proven Mobile Application Development expertise.</p><p>Technology can make or break companies. Efficient, User-friendly online apps directly impact your revenue. At Equator Technologies, we are aware of this phenomenon and can provide a complete range of solutions for your e-commerce business needs. From web applications to mobile apps to software testing, we provide an array of software development and maintenance services.</p><p>Our technical prowess and extensive experience gives us an edge over our competitors. And that’s not all. We are committed to consistently offering the best IT solutions and enterprise mobility solutions. We understand your company’s budget limitations. That’s why our experts design customized plans to suit your goals, interests and financial needs. We are a rapidly expanding and credible enterprise solution provider. Our top-notch services will not just streamline your workflow, but boost your online presence as well. After all, our goal is to provide swift solutions that are free from hassle! Browse through our services and choose the one that meets your business goals.</p>"
            },
            {
                "submenuName" : "Folder 3",
                "info" : "<b>Folder 3</b><br><br><h3>E-commerce Solution</h3><p>Our software developers are highly skilled in developing the most innovative & modern E-commerce apps. Our software developers also come up with powerful strategies to expand our client’s customer base. </p><p>Technology can make or break companies. Efficient, User-friendly online apps directly impact your revenue. At Equator Technologies, we are aware of this phenomenon and can provide a complete range of solutions for your e-commerce business needs. From web applications to mobile apps to software testing, we provide an array of software development and maintenance services.</p><p>Our technical prowess and extensive experience gives us an edge over our competitors. And that’s not all. We are committed to consistently offering the best IT solutions and enterprise mobility solutions. We understand your company’s budget limitations. That’s why our experts design customized plans to suit your goals, interests and financial needs. We are a rapidly expanding and credible enterprise solution provider. Our top-notch services will not just streamline your workflow, but boost your online presence as well. After all, our goal is to provide swift solutions that are free from hassle! Browse through our services and choose the one that meets your business goals.</p>"
            }            
        ]
    },
    {
        "menuName" : "Tags",
        "hierarchy" : 3,
        "info" : "<b>Tags</b><br><br><p>Technology can make or break companies. Efficient, User-friendly online apps directly impact your revenue. At Equator Technologies, we are aware of this phenomenon and can provide a complete range of solutions for your e-commerce business needs. From web applications to mobile apps to software testing, we provide an array of software development and maintenance services.</p><p>Our technical prowess and extensive experience gives us an edge over our competitors. And that’s not all. We are committed to consistently offering the best IT solutions and enterprise mobility solutions. We understand your company’s budget limitations. That’s why our experts design customized plans to suit your goals, interests and financial needs. We are a rapidly expanding and credible enterprise solution provider. Our top-notch services will not just streamline your workflow, but boost your online presence as well. After all, our goal is to provide swift solutions that are free from hassle! Browse through our services and choose the one that meets your business goals.</p>"
    },
    {
        "menuName" : "Document Types",
        "hierarchy" : 4,
        "subMenu" :
        [
            {
                "submenuName" : "Doc Type 1",
                "info" : "<b>Doc Type 1</b><br><br><h3>Web Application Development</h3><p>At Equator Technologies, we develop Web Applications which meet the expectations of modern day enterprises. Our web developers deliver exceptional user experience with extreme reliability & high scalability.</p>Technology can make or break companies. Efficient, User-friendly online apps directly impact your revenue. At Equator Technologies, we are aware of this phenomenon and can provide a complete range of solutions for your e-commerce business needs. From web applications to mobile apps to software testing, we provide an array of software development and maintenance services.</p><p>Our technical prowess and extensive experience gives us an edge over our competitors. And that’s not all. We are committed to consistently offering the best IT solutions and enterprise mobility solutions. We understand your company’s budget limitations. That’s why our experts design customized plans to suit your goals, interests and financial needs. We are a rapidly expanding and credible enterprise solution provider. Our top-notch services will not just streamline your workflow, but boost your online presence as well. After all, our goal is to provide swift solutions that are free from hassle! Browse through our services and choose the one that meets your business goals.</p>"
            },
            {
                "submenuName" : "Doc Type 2",
                "info" : "<b>Doc Type 2</b><br><br><h3>Mobile Application Development</h3><p>We specialize in creating Native applications for iOS & Android. We also develop hybrid mobile applications which could be deployed across almost all mobile platforms. We have proven Mobile Application Development expertise.</p><p>Technology can make or break companies. Efficient, User-friendly online apps directly impact your revenue. At Equator Technologies, we are aware of this phenomenon and can provide a complete range of solutions for your e-commerce business needs. From web applications to mobile apps to software testing, we provide an array of software development and maintenance services.</p><p>Our technical prowess and extensive experience gives us an edge over our competitors. And that’s not all. We are committed to consistently offering the best IT solutions and enterprise mobility solutions. We understand your company’s budget limitations. That’s why our experts design customized plans to suit your goals, interests and financial needs. We are a rapidly expanding and credible enterprise solution provider. Our top-notch services will not just streamline your workflow, but boost your online presence as well. After all, our goal is to provide swift solutions that are free from hassle! Browse through our services and choose the one that meets your business goals.</p>"
            },
            {
                "submenuName" : "Doc Type 3",
                "info" : "<b>Doc Type 3</b><br><br><h3>E-commerce Solution</h3><p>Our software developers are highly skilled in developing the most innovative & modern E-commerce apps. Our software developers also come up with powerful strategies to expand our client’s customer base. </p><p>Technology can make or break companies. Efficient, User-friendly online apps directly impact your revenue. At Equator Technologies, we are aware of this phenomenon and can provide a complete range of solutions for your e-commerce business needs. From web applications to mobile apps to software testing, we provide an array of software development and maintenance services.</p><p>Our technical prowess and extensive experience gives us an edge over our competitors. And that’s not all. We are committed to consistently offering the best IT solutions and enterprise mobility solutions. We understand your company’s budget limitations. That’s why our experts design customized plans to suit your goals, interests and financial needs. We are a rapidly expanding and credible enterprise solution provider. Our top-notch services will not just streamline your workflow, but boost your online presence as well. After all, our goal is to provide swift solutions that are free from hassle! Browse through our services and choose the one that meets your business goals.</p>"
            }            
        ]
    },
    {
        "menuName" : "Stack Types",
        "hierarchy" : 5,
        "info" : "<b>Stack Types</b><br><br><p>Technology can make or break companies. Efficient, User-friendly online apps directly impact your revenue. At Equator Technologies, we are aware of this phenomenon and can provide a complete range of solutions for your e-commerce business needs. From web applications to mobile apps to software testing, we provide an array of software development and maintenance services.</p><p>Our technical prowess and extensive experience gives us an edge over our competitors. And that’s not all. We are committed to consistently offering the best IT solutions and enterprise mobility solutions. We understand your company’s budget limitations. That’s why our experts design customized plans to suit your goals, interests and financial needs. We are a rapidly expanding and credible enterprise solution provider. Our top-notch services will not just streamline your workflow, but boost your online presence as well. After all, our goal is to provide swift solutions that are free from hassle! Browse through our services and choose the one that meets your business goals.</p>"
    }
];